"""Every function SnowDuck documents must at least execute.

This is deliberately a breadth check rather than a correctness one - the exact
results that differ from a naive translation are pinned in
``test_snowflake_semantics``. Its job is to stop the documented function list
drifting away from what actually works.
"""

import pytest

CASES = [
    "SELECT UNIFORM(1, 10, RANDOM())",
    "SELECT CORR(x, y) FROM (SELECT 1 x, 2 y)",
    "SELECT PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY x) FROM (SELECT 1 x)",
    "SELECT MODE(x) FROM (SELECT 1 x)",
    "SELECT VARIANCE(x) FROM (SELECT 1.0 x UNION ALL SELECT 2.0)",
    "SELECT STDDEV_POP(x) FROM (SELECT 1.0 x UNION ALL SELECT 2.0)",
    "SELECT LOG10(100)",
    "SELECT TRUNC(1.75, 1)",
    "SELECT POW(2,3)",
    "SELECT CEILING(1.2)",
    "SELECT MONTHS_BETWEEN(TO_DATE('2024-03-01'), TO_DATE('2024-01-01'))",
    "SELECT TO_TIME('10:00:00')",
    "SELECT GETDATE()",
    "SELECT SYSDATE()",
    "SELECT DAYOFWEEK(TO_DATE('2024-01-01'))",
    "SELECT WEEKOFYEAR(TO_DATE('2024-06-01'))",
    "SELECT QUARTER(TO_DATE('2024-06-01'))",
    "SELECT DAYOFYEAR(TO_DATE('2024-02-01'))",
    "SELECT TO_VARIANT(1)",
    "SELECT CHECK_JSON('{}')",
    "SELECT OBJECT_KEYS(OBJECT_CONSTRUCT('a',1))",
    "SELECT ARRAY_CAT(ARRAY_CONSTRUCT(1),ARRAY_CONSTRUCT(2))",
    "SELECT ARRAY_APPEND(ARRAY_CONSTRUCT(1),2)",
    "SELECT ARRAY_PREPEND(ARRAY_CONSTRUCT(1),0)",
    "SELECT ARRAY_SORT(ARRAY_CONSTRUCT(2,1))",
    "SELECT ARRAY_DISTINCT(ARRAY_CONSTRUCT(1,1))",
    "SELECT ARRAY_INTERSECTION(ARRAY_CONSTRUCT(1,2),ARRAY_CONSTRUCT(2))",
    "SELECT ARRAY_EXCEPT(ARRAY_CONSTRUCT(1,2),ARRAY_CONSTRUCT(2))",
    "SELECT ARRAYS_OVERLAP(ARRAY_CONSTRUCT(1),ARRAY_CONSTRUCT(1))",
    "SELECT ARRAY_MIN(ARRAY_CONSTRUCT(2,1))",
    "SELECT ARRAY_MAX(ARRAY_CONSTRUCT(2,1))",
    "SELECT ARRAY_SUM(ARRAY_CONSTRUCT(1,2))",
    "SELECT ARRAY_CONTAINS(1::VARIANT, ARRAY_CONSTRUCT(1))",
    "SELECT ARRAY_REVERSE(ARRAY_CONSTRUCT(1,2))",
    "SELECT ARRAY_COMPACT(ARRAY_CONSTRUCT(1,NULL))",
    "SELECT SHA1('a')",
    "SELECT SHA2('a',256)",
    "SELECT HASH('a')",
    "SELECT MD5('a')",
    "SELECT BITAND(1,3)",
    "SELECT BITOR(1,2)",
    "SELECT BITXOR(1,3)",
    "SELECT BITNOT(1)",
    "SELECT BOOLAND_AGG(x) FROM (SELECT TRUE x)",
    "SELECT BOOLOR_AGG(x) FROM (SELECT TRUE x)",
    "SELECT BITAND_AGG(x) FROM (SELECT 3 x)",
    "SELECT SPACE(3)",
    "SELECT STRTOK('a b',' ',1)",
    "SELECT TRANSLATE('abc','a','x')",
    "SELECT ASCII('a')",
    "SELECT CHR(97)",
    "SELECT SOUNDEX('Robert')",
    "SELECT INSTR('abc','b')",
    "SELECT KURTOSIS(x) FROM (SELECT 1.0 x UNION ALL SELECT 2.0 UNION ALL SELECT 3.0 UNION ALL SELECT 9.0)",
    "SELECT SKEW(x) FROM (SELECT 1.0 x UNION ALL SELECT 2.0 UNION ALL SELECT 9.0)",
    "SELECT CONVERT_TIMEZONE('UTC','America/New_York', TO_TIMESTAMP('2024-01-01 10:00:00'))",
    "SELECT DATE_FROM_PARTS(2024,1,1)",
    "SELECT TIME_FROM_PARTS(10,0,0)",
    "SELECT TIMESTAMP_FROM_PARTS(2024,1,1,10,0,0)",
    "SELECT ADD_MONTHS(TO_DATE('2024-01-31'),1)",
    "SELECT WIDTH_BUCKET(5,0,10,2)",
    "SELECT FACTORIAL(5)",
    "SELECT CBRT(27)",
    "SELECT DEGREES(PI())",
    "SELECT RADIANS(180)",
    "SELECT NULLIFZERO(0)",
    "SELECT ZEROIFNULL(NULL)",
    "SELECT BASE64_ENCODE('a')",
    "SELECT BASE64_DECODE_STRING('YQ==')",
    "SELECT HEX_ENCODE('a')",
    "SELECT HEX_DECODE_STRING('61')",
    "SELECT UUID_STRING()",
    "SELECT TYPEOF(1)",
    "SELECT TO_JSON(OBJECT_CONSTRUCT('a',1))",
    "SELECT CHARINDEX('b','abc')",
    "SELECT LEN('abc')",
    "SELECT REVERSE('abc')",
]


@pytest.mark.parametrize("sql", CASES)
def test_documented_function_executes(conn, sql):
    with conn.cursor() as cur:
        cur.execute(sql)
        cur.fetchone()
