"""Snowflake -> DuckDB translation.

Translation happens in two stages:

1. **AST rewrites** (:mod:`snowduck.dialect.preprocess`) turn Snowflake nodes
   into DuckDB-equivalent nodes. Almost everything lives here.
2. **Statement rewrites** (:mod:`snowduck.dialect.transforms`) handle whole
   statements that have no DuckDB AST at all - ``SHOW``, ``USE``,
   ``CREATE DATABASE`` (an ``ATTACH``), ``DESCRIBE`` (an information-schema
   query). These produce SQL text directly.

Everything else is generated by sqlglot's stock DuckDB generator.

:class:`Dialect` deliberately does **not** subclass ``DuckDB.Generator``:
sqlglot ships mypyc-compiled generators, and a compiled class cannot be
subclassed from Python. Customisation is done by overriding
:meth:`Dialect.generate`, which stays interpreted.
"""

import logging
from collections import OrderedDict
from typing import Any

from sqlglot import exp
from sqlglot.dialects import DuckDB

from .context import DialectContext
from .preprocess import (
    preprocess_arrays,
    preprocess_bitwise,
    preprocess_case_folding,
    preprocess_current_schema,
    preprocess_date_functions,
    preprocess_functions,
    preprocess_generator,
    preprocess_identifier,
    preprocess_info_schema,
    preprocess_number_formats,
    preprocess_regexp,
    preprocess_semi_structured,
    preprocess_seq_functions,
    preprocess_session_info,
    preprocess_special_expressions,
    preprocess_syntax,
    preprocess_system_calls,
    preprocess_timestamp_literals,
    preprocess_variables,
)
from .transforms import (
    transform_alter,
    transform_command,
    transform_copy,
    transform_create,
    transform_describe,
    transform_drop,
    transform_set,
    transform_show,
    transform_truncate,
    transform_use,
)

# Applied in order. Ordering matters in four places: case folding runs first,
# so it only ever sees identifiers the user wrote and not ones a later rewrite
# synthesised; date handling must run before `special_expressions`, so string
# literals are already cast to DATE; `syntax` must run before `functions`, so
# rewritten nodes are seen by both; and `number_formats` must run before
# `date_functions`, which would otherwise cast TO_CHAR's numeric argument.
_PREPROCESSORS = (
    preprocess_case_folding,
    preprocess_variables,
    preprocess_identifier,
    preprocess_info_schema,
    preprocess_number_formats,
    preprocess_current_schema,
    preprocess_session_info,
    preprocess_system_calls,
    preprocess_arrays,
    preprocess_semi_structured,
    preprocess_generator,
    preprocess_seq_functions,
    preprocess_bitwise,
    preprocess_regexp,
    preprocess_date_functions,
    preprocess_timestamp_literals,
    preprocess_syntax,
    preprocess_functions,
    preprocess_special_expressions,
)

_CacheKey = tuple[
    str,
    "str | None",
    "str | None",
    "str | None",
    "str | None",
    str,
    str,
    tuple[tuple[str, str], ...],
    tuple[tuple[str, str], ...],
]

# Whole statements with no DuckDB AST equivalent, rendered as SQL text.
_STATEMENT_TRANSFORMS: dict[type[exp.Expression], Any] = {
    exp.Show: transform_show,
    exp.Create: transform_create,
    exp.Describe: transform_describe,
    exp.Use: transform_use,
    exp.Copy: transform_copy,
    exp.Set: transform_set,
    exp.Command: transform_command,
    exp.Alter: transform_alter,
    exp.Drop: transform_drop,
    exp.TruncateTable: transform_truncate,
}


_SQLGLOT_LOGGER = logging.getLogger("sqlglot")


class _Quiet(logging.Filter):
    def filter(self, record: logging.LogRecord) -> bool:
        return False


def _rendered_quietly(expression: exp.Expression) -> str:
    """Render an expression back to Snowflake, without sqlglot's commentary.

    This is an internal round trip - the cache key - not something the caller
    ever sees, so a warning sqlglot's *Snowflake* generator raises about its own
    output is pure noise. `ALTER TABLE ... ALTER COLUMN c SET NOT NULL` is one:
    it warns "Unsupported ALTER COLUMN syntax" while SnowDuck translates the
    statement correctly, so the message only teaches the reader to ignore
    warnings that do matter.
    """
    quiet = _Quiet()
    _SQLGLOT_LOGGER.addFilter(quiet)
    try:
        return str(expression.sql(dialect="snowflake"))
    finally:
        _SQLGLOT_LOGGER.removeFilter(quiet)


class Dialect(DuckDB):  # type: ignore[misc]
    """DuckDB, extended with Snowflake semantics and session context."""

    _SQL_CACHE: "OrderedDict[_CacheKey, str]" = OrderedDict()
    _SQL_CACHE_MAX = 1024

    def __init__(self, context: DialectContext):
        super().__init__()
        self._context = context

    @property
    def context(self) -> DialectContext:
        return self._context

    # -- translation --------------------------------------------------------

    def preprocess(self, expression: exp.Expression) -> exp.Expression:
        """Apply every Snowflake -> DuckDB AST rewrite, in order."""
        for rewrite in _PREPROCESSORS:
            expression = expression.transform(rewrite, context=self._context)
        return expression

    def generate(
        self, expression: exp.Expression, copy: bool = True, **opts: Any
    ) -> str:
        """Translate a Snowflake expression into DuckDB SQL."""
        if copy:
            expression = expression.copy()

        expression = self.preprocess(expression)

        statement_transform = _STATEMENT_TRANSFORMS.get(type(expression))
        if statement_transform is not None:
            return str(statement_transform(expression, context=self._context))

        return str(super().generate(expression, copy=False, **opts))

    # -- cache --------------------------------------------------------------

    @classmethod
    def clear_cache(cls) -> None:
        cls._SQL_CACHE.clear()

    @classmethod
    def cache_size(cls) -> int:
        return len(cls._SQL_CACHE)

    @classmethod
    def _cache_key(cls, snowflake_sql: str, context: DialectContext) -> "_CacheKey":
        # Session parameters and variables are part of the key: SHOW PARAMETERS
        # and SHOW VARIABLES render their current values straight into the SQL,
        # so a key without them would serve a stale answer after ALTER SESSION.
        return (
            snowflake_sql,
            context.current_database,
            context.current_schema,
            context.current_role,
            context.current_warehouse,
            context.info_schema_manager.account_catalog_name,
            context.info_schema_manager.info_schema_name,
            tuple(sorted(context.session_parameters.items())),
            tuple(sorted(context.session_variables.items())),
        )

    @classmethod
    def sql_with_cache(cls, expression: exp.Expression, dialect: "Dialect") -> str:
        snowflake_sql = _rendered_quietly(expression)

        # Don't cache queries with variable substitutions (they can change frequently)
        has_variables = bool(
            expression.find(exp.Parameter) or expression.find(exp.Placeholder)
        )
        if has_variables:
            return expression.sql(dialect=dialect)

        # SHOW renders some results as literals read from outside the catalog -
        # SHOW STAGES lists the stage directory - so its SQL is not a pure
        # function of the cache key. Rendering it is cheap; caching it is wrong.
        if isinstance(expression, (exp.Show, exp.Command)):
            return expression.sql(dialect=dialect)

        key = cls._cache_key(snowflake_sql, dialect.context)
        cached = cls._SQL_CACHE.get(key)
        if cached is not None:
            cls._SQL_CACHE.move_to_end(key)
            return cached

        sql = expression.sql(dialect=dialect)
        cls._SQL_CACHE[key] = sql
        if len(cls._SQL_CACHE) > cls._SQL_CACHE_MAX:
            cls._SQL_CACHE.popitem(last=False)
        return sql
